"""
markov_transition_table.py

Movement history / Markov transition table for GajaAlert.
Stores two related datasets:
  1. movement_history — the raw sequence of zone-to-zone transitions
     generated by the correlated random walk elephant movement
     simulation.
  2. transition_matrix — the normalized probability matrix (TPM)
     derived from that history, used to predict the probability of
     a herd being in a neighbouring zone within the next 6-12 hours.
"""

# Raw movement history: each entry is one recorded transition
# by a simulated (or tracked) herd from one zone to another.
movement_history = [
    {"herd_id": "H01", "timestamp": "2026-08-10 06:00", "from_zone": "Z01", "to_zone": "Z01"},
    {"herd_id": "H01", "timestamp": "2026-08-10 12:00", "from_zone": "Z01", "to_zone": "Z02"},
    {"herd_id": "H01", "timestamp": "2026-08-10 18:00", "from_zone": "Z02", "to_zone": "Z02"},
    {"herd_id": "H02", "timestamp": "2026-08-10 06:00", "from_zone": "Z03", "to_zone": "Z04"},
    {"herd_id": "H02", "timestamp": "2026-08-10 12:00", "from_zone": "Z04", "to_zone": "Z03"},
    {"herd_id": "H02", "timestamp": "2026-08-10 18:00", "from_zone": "Z03", "to_zone": "Z03"},
]

# Derived transition probability matrix (TPM), as per Appendix D.
# Each entry: probability of moving from current_zone to each
# neighbouring zone (including staying) within the next 6-12 hours.
transition_matrix = [
    {"current_zone": "Z01", "P_stay": 0.55, "P_neighbour_A": 0.30, "neighbour_A": "Z02", "P_neighbour_B": 0.15, "neighbour_B": "Z05"},
    {"current_zone": "Z02", "P_stay": 0.20, "P_neighbour_A": 0.60, "neighbour_A": "Z01", "P_neighbour_B": 0.20, "neighbour_B": "Z03"},
    {"current_zone": "Z03", "P_stay": 0.10, "P_neighbour_A": 0.35, "neighbour_A": "Z04", "P_neighbour_B": 0.55, "neighbour_B": "Z02"},
]


def get_history_for_herd(herd_id):
    """Return all movement history entries for a given herd."""
    return [entry for entry in movement_history if entry["herd_id"] == herd_id]


def get_transition_row(zone_id):
    """Return the transition probability row for a given zone, or None."""
    for row in transition_matrix:
        if row["current_zone"] == zone_id:
            return row
    return None


def predict_next_zones(zone_id):
    """
    Return a dict of {zone: probability} for the most likely zones a
    herd currently in `zone_id` will be in during the next 6-12 hours.
    """
    row = get_transition_row(zone_id)
    if not row:
        return {}
    return {
        zone_id: row["P_stay"],
        row["neighbour_A"]: row["P_neighbour_A"],
        row["neighbour_B"]: row["P_neighbour_B"],
    }


if __name__ == "__main__":
    print("Movement history for H01:", get_history_for_herd("H01"))
    print("\nTransition row for Z03:", get_transition_row("Z03"))
    print("\nPredicted next zones for Z03:", predict_next_zones("Z03"))