RULES = [
    {"id": "R1", "sighting": "High", "distance": "Near", "time": "Night", "season": "High", "risk": "High"},
    {"id": "R2", "sighting": "High", "distance": "Near", "time": "Night", "season": "Medium", "risk": "High"},
    {"id": "R3", "sighting": "High", "distance": "Near", "time": "Night", "season": "Low", "risk": "High"},
    {"id": "R4", "sighting": "High", "distance": "Medium", "time": "Night", "season": "High", "risk": "High"},
    {"id": "R5", "sighting": "High", "distance": "Medium", "time": "Night", "season": "Medium", "risk": "Medium/High"},
    {"id": "R6", "sighting": "High", "distance": "Far", "time": "Night", "season": "High", "risk": "Medium/High"},
    {"id": "R7", "sighting": "Medium", "distance": "Near", "time": "Night", "season": "High", "risk": "High"},
    {"id": "R8", "sighting": "Medium", "distance": "Near", "time": "Night", "season": "Medium", "risk": "Medium/High"},
    {"id": "R9", "sighting": "Medium", "distance": "Medium", "time": "Night", "season": "High", "risk": "Medium/High"},
    {"id": "R10", "sighting": "Low", "distance": "Near", "time": "Night", "season": "High", "risk": "Medium"},
    {"id": "R11", "sighting": "Low", "distance": "Near", "time": "Night", "season": "Medium", "risk": "Medium"},
    {"id": "R12", "sighting": "Low", "distance": "Far", "time": "Night", "season": "Low", "risk": "Low"},
    {"id": "R13", "sighting": "High", "distance": "Near", "time": "Dusk", "season": "High", "risk": "High"},
    {"id": "R14", "sighting": "High", "distance": "Medium", "time": "Dusk", "season": "High", "risk": "High"},
    {"id": "R15", "sighting": "Medium", "distance": "Near", "time": "Dusk", "season": "High", "risk": "High"},
    {"id": "R16", "sighting": "Medium", "distance": "Near", "time": "Dusk", "season": "Medium", "risk": "Medium"},
    {"id": "R17", "sighting": "Medium", "distance": "Far", "time": "Dusk", "season": "Medium", "risk": "Medium"},
    {"id": "R18", "sighting": "Low", "distance": "Near", "time": "Dusk", "season": "High", "risk": "Medium"},
    {"id": "R19", "sighting": "Low", "distance": "Near", "time": "Dusk", "season": "Medium", "risk": "Medium"},
    {"id": "R20", "sighting": "Low", "distance": "Medium", "time": "Dusk", "season": "Low", "risk": "Low"},
    {"id": "R21", "sighting": "Low", "distance": "Far", "time": "Dusk", "season": "Low", "risk": "Low"},
    {"id": "R22", "sighting": "High", "distance": "Near", "time": "Day", "season": "High", "risk": "Medium/High"},
    {"id": "R23", "sighting": "High", "distance": "Far", "time": "Day", "season": "High", "risk": "Medium"},
    {"id": "R24", "sighting": "Medium", "distance": "Near", "time": "Day", "season": "Medium", "risk": "Medium"},
    {"id": "R25", "sighting": "Medium", "distance": "Far", "time": "Day", "season": "Low", "risk": "Low"},
    {"id": "R26", "sighting": "Low", "distance": "Medium", "time": "Day", "season": "Low", "risk": "Low"},
    {"id": "R27", "sighting": "Low", "distance": "Far", "time": "Day", "season": "Low", "risk": "Low"},

    # ------------------------------------------------------------------
    # DERIVED RULES (D01-D54): fill every combination the expert rules above
    # do not cover, so all 81 combinations (3 x 3 x 3 x 3) have a result.
    # Score = 4*sighting + 2*distance + 2*time + 1*season, where each factor
    # is 0 (Low/Far/Day) / 1 (Medium/Dusk) / 2 (High/Near/Night).
    # Score < 7 Low | 7-10 Medium | 11-15 Medium/High | 16+ High.
    # Expert rules R1-R27 always take priority (they are listed first).
    # Review the derived rules with a DWC officer before final submission.
    # ------------------------------------------------------------------
    {"id": "D01", "sighting": "High", "distance": "Near", "time": "Dusk", "season": "Medium", "risk": "Medium/High"},
    {"id": "D02", "sighting": "High", "distance": "Near", "time": "Dusk", "season": "Low", "risk": "Medium/High"},
    {"id": "D03", "sighting": "High", "distance": "Near", "time": "Day", "season": "Medium", "risk": "Medium/High"},
    {"id": "D04", "sighting": "High", "distance": "Near", "time": "Day", "season": "Low", "risk": "Medium/High"},
    {"id": "D05", "sighting": "High", "distance": "Medium", "time": "Night", "season": "Low", "risk": "Medium/High"},
    {"id": "D06", "sighting": "High", "distance": "Medium", "time": "Dusk", "season": "Medium", "risk": "Medium/High"},
    {"id": "D07", "sighting": "High", "distance": "Medium", "time": "Dusk", "season": "Low", "risk": "Medium/High"},
    {"id": "D08", "sighting": "High", "distance": "Medium", "time": "Day", "season": "High", "risk": "Medium/High"},
    {"id": "D09", "sighting": "High", "distance": "Medium", "time": "Day", "season": "Medium", "risk": "Medium/High"},
    {"id": "D10", "sighting": "High", "distance": "Medium", "time": "Day", "season": "Low", "risk": "Medium"},
    {"id": "D11", "sighting": "High", "distance": "Far", "time": "Night", "season": "Medium", "risk": "Medium/High"},
    {"id": "D12", "sighting": "High", "distance": "Far", "time": "Night", "season": "Low", "risk": "Medium/High"},
    {"id": "D13", "sighting": "High", "distance": "Far", "time": "Dusk", "season": "High", "risk": "Medium/High"},
    {"id": "D14", "sighting": "High", "distance": "Far", "time": "Dusk", "season": "Medium", "risk": "Medium/High"},
    {"id": "D15", "sighting": "High", "distance": "Far", "time": "Dusk", "season": "Low", "risk": "Medium"},
    {"id": "D16", "sighting": "High", "distance": "Far", "time": "Day", "season": "Medium", "risk": "Medium"},
    {"id": "D17", "sighting": "High", "distance": "Far", "time": "Day", "season": "Low", "risk": "Medium"},
    {"id": "D18", "sighting": "Medium", "distance": "Near", "time": "Night", "season": "Low", "risk": "Medium/High"},
    {"id": "D19", "sighting": "Medium", "distance": "Near", "time": "Dusk", "season": "Low", "risk": "Medium"},
    {"id": "D20", "sighting": "Medium", "distance": "Near", "time": "Day", "season": "High", "risk": "Medium"},
    {"id": "D21", "sighting": "Medium", "distance": "Near", "time": "Day", "season": "Low", "risk": "Medium"},
    {"id": "D22", "sighting": "Medium", "distance": "Medium", "time": "Night", "season": "Medium", "risk": "Medium/High"},
    {"id": "D23", "sighting": "Medium", "distance": "Medium", "time": "Night", "season": "Low", "risk": "Medium"},
    {"id": "D24", "sighting": "Medium", "distance": "Medium", "time": "Dusk", "season": "High", "risk": "Medium"},
    {"id": "D25", "sighting": "Medium", "distance": "Medium", "time": "Dusk", "season": "Medium", "risk": "Medium"},
    {"id": "D26", "sighting": "Medium", "distance": "Medium", "time": "Dusk", "season": "Low", "risk": "Medium"},
    {"id": "D27", "sighting": "Medium", "distance": "Medium", "time": "Day", "season": "High", "risk": "Medium"},
    {"id": "D28", "sighting": "Medium", "distance": "Medium", "time": "Day", "season": "Medium", "risk": "Medium"},
    {"id": "D29", "sighting": "Medium", "distance": "Medium", "time": "Day", "season": "Low", "risk": "Low"},
    {"id": "D30", "sighting": "Medium", "distance": "Far", "time": "Night", "season": "High", "risk": "Medium"},
    {"id": "D31", "sighting": "Medium", "distance": "Far", "time": "Night", "season": "Medium", "risk": "Medium"},
    {"id": "D32", "sighting": "Medium", "distance": "Far", "time": "Night", "season": "Low", "risk": "Medium"},
    {"id": "D33", "sighting": "Medium", "distance": "Far", "time": "Dusk", "season": "High", "risk": "Medium"},
    {"id": "D34", "sighting": "Medium", "distance": "Far", "time": "Dusk", "season": "Low", "risk": "Low"},
    {"id": "D35", "sighting": "Medium", "distance": "Far", "time": "Day", "season": "High", "risk": "Low"},
    {"id": "D36", "sighting": "Medium", "distance": "Far", "time": "Day", "season": "Medium", "risk": "Low"},
    {"id": "D37", "sighting": "Low", "distance": "Near", "time": "Night", "season": "Low", "risk": "Medium"},
    {"id": "D38", "sighting": "Low", "distance": "Near", "time": "Dusk", "season": "Low", "risk": "Low"},
    {"id": "D39", "sighting": "Low", "distance": "Near", "time": "Day", "season": "High", "risk": "Low"},
    {"id": "D40", "sighting": "Low", "distance": "Near", "time": "Day", "season": "Medium", "risk": "Low"},
    {"id": "D41", "sighting": "Low", "distance": "Near", "time": "Day", "season": "Low", "risk": "Low"},
    {"id": "D42", "sighting": "Low", "distance": "Medium", "time": "Night", "season": "High", "risk": "Medium"},
    {"id": "D43", "sighting": "Low", "distance": "Medium", "time": "Night", "season": "Medium", "risk": "Medium"},
    {"id": "D44", "sighting": "Low", "distance": "Medium", "time": "Night", "season": "Low", "risk": "Low"},
    {"id": "D45", "sighting": "Low", "distance": "Medium", "time": "Dusk", "season": "High", "risk": "Low"},
    {"id": "D46", "sighting": "Low", "distance": "Medium", "time": "Dusk", "season": "Medium", "risk": "Low"},
    {"id": "D47", "sighting": "Low", "distance": "Medium", "time": "Day", "season": "High", "risk": "Low"},
    {"id": "D48", "sighting": "Low", "distance": "Medium", "time": "Day", "season": "Medium", "risk": "Low"},
    {"id": "D49", "sighting": "Low", "distance": "Far", "time": "Night", "season": "High", "risk": "Low"},
    {"id": "D50", "sighting": "Low", "distance": "Far", "time": "Night", "season": "Medium", "risk": "Low"},
    {"id": "D51", "sighting": "Low", "distance": "Far", "time": "Dusk", "season": "High", "risk": "Low"},
    {"id": "D52", "sighting": "Low", "distance": "Far", "time": "Dusk", "season": "Medium", "risk": "Low"},
    {"id": "D53", "sighting": "Low", "distance": "Far", "time": "Day", "season": "High", "risk": "Low"},
    {"id": "D54", "sighting": "Low", "distance": "Far", "time": "Day", "season": "Medium", "risk": "Low"},
]
